channels:
- conda-forge
- defaults
- nodefaults
dependencies:
- cantera
- make
- mypy
- myst-parser
- numpy
- pandas
- pint
- pip
- plotly
- pre-commit
- pydantic>=2.0.0
- pydata-sphinx-theme
- pytest
- pytest-cov
- python=3.11
- sphinx
- sphinx-autoapi
- sphinx-gallery
- pip:
  - pytest-html>=3.0.0
  - pytest-mock>=3.0.0
  - pytest-xvfb
  - types-PyYAML>=6.0.0
name: boulder
